version: '3.4'
services:
# There are the servers applications

  # database server
  db:
    image: luisaraujo/springbootdb:2.0.2
    # Commands should be done:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    
    # Build the file
    build:
      # Directory when the file was created
      context: .
      dockerfile: Dockerfile
    # Server configs:
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: 1q2w3e4r5t
      MYSQL_DATABASE: restSpringboot
    ports:
      - "3308:3306"
    networks:
      - devsecops-network
  
  # application Server
  SpringBootApi:
    image: luisaraujo/springbootapp:2.0.2
    restart: always
    build: ./SpringBootRestApi
    working_dir: /SpringBootRestApi
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./SpringBootRestApi:/SpringBootRestApi
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - devsecops-network
networks:
    devsecops-network:
        driver: bridge
